<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:atm="http://temenos.com/ATM.SERVICES">
	<soapenv:Header/>
	<soapenv:Body>
		<atm:BalanceEnquiryWebservice>
			<WebRequestCommon>
				<company>${body.requestPayload.additionalData.companyCode!""}</company>
				<password>${body.providerPassword!""}</password>
				<userName>${body.providerUsername!""}</userName>
			</WebRequestCommon>
			<KCBRWATMBALENQType>
				<enquiryInputCollection>
					<columnName>ACCOUNT</columnName>
					<criteriaValue>${body.requestPayload.primaryData.businessKey!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
				<enquiryInputCollection>
					<columnName>L.SERVICE.CODE</columnName>
					<criteriaValue>${body.header.serviceCode!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
				<enquiryInputCollection>
					<columnName>L.RRN</columnName>
					<criteriaValue>${body.requestPayload.additionalData.rrn!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
				<enquiryInputCollection>
					<columnName>L.CHANNEL.CODE</columnName>
					<criteriaValue>${body.header.channelCode!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
				<enquiryInputCollection>
					<columnName>L.UNIQUE.REF</columnName>
					<criteriaValue>${body.requestPayload.additionalData.uniqueRef!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
				<enquiryInputCollection>
					<columnName>L.SESSION.ID</columnName>
					<criteriaValue>${body.requestPayload.additionalData.sessionID!""}</criteriaValue>
					<operand>EQ</operand>
				</enquiryInputCollection>
			</KCBRWATMBALENQType>
		</atm:BalanceEnquiryWebservice>
	</soapenv:Body>
</soapenv:Envelope>
