kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: atomic-consulta-saldo
spec:
  to:
    kind: Service
    name: atomic-consulta-saldo
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None